(define (problem jocProva5) (:domain planificador4)
(:objects
    p0 p1 p2 p3 - programador
    t0 t1 t2 t3 - tasca
)
(:init
    (= (tasques_assignades) 0)
    (= (suma_hores) 0)
    (= (programadors) 0)
    (= (habilitat p0) 2)
    (= (habilitat p1) 2)
    (= (habilitat p2) 2)
    (= (habilitat p3) 1)
    (= (qualitat p0) 2)
    (= (qualitat p1) 1)
    (= (qualitat p2) 2)
    (= (qualitat p3) 2)
    (= (noves_assginacions p0) 2)
    (= (noves_assginacions p1) 2)
    (= (noves_assginacions p2) 2)
    (= (noves_assginacions p3) 2)
    (= (dificultat t0) 2)
    (= (dificultat t1) 3)
    (= (dificultat t2) 2)
    (= (dificultat t3) 3)
    (= (duracio_tasca t0) 4)
    (= (duracio_tasca t1) 1)
    (= (duracio_tasca t2) 3)
    (= (duracio_tasca t3) 8)
    (tasca_oberta t0)
    (tasca_oberta t1)
    (tasca_oberta t2)
    (tasca_oberta t3)
)
(:goal
    (= (tasques_assignades) 4)
)
(:metric minimize (+ (* 4 (suma_hores)) (* 16 (programadors))))
)